name: Sync Upstream and Build Android Binary for Cloudreve

on:
  schedule:
    # 每天执行一次 (UTC 时间)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Upstream Tag
        id: get_latest_tag
        run: |
          latest_tag=$(curl --silent "https://api.github.com/repos/cloudreve/Cloudreve/releases/latest" | jq -r .tag_name)
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV
          echo "Latest upstream tag is: ${latest_tag}"

      - name: Checkout Your Repository
        uses: actions/checkout@v4
        with:
          # 使用 personal access token (PAT) 以便可以推送到仓库
          # 请在仓库的 Settings > Secrets and variables > Actions 中配置名为 GH_PAT 的 secret
          token: ${{ secrets.GH_PAT }}

      - name: Check if Release Already Exists
        id: check_release
        run: |
          if gh release view ${{ env.latest_tag }}; then
            echo "Release ${{ env.latest_tag }} already exists. Exiting."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Release ${{ env.latest_tag }} does not exist. Proceeding with build."
            echo "exists=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone Upstream Cloudreve Repository
        if: env.exists == 'false'
        uses: actions/checkout@v4
        with:
          repository: cloudreve/Cloudreve
          ref: ${{ env.latest_tag }}
          path: cloudreve-source
          submodules: 'recursive'

      - name: Set up Go
        if: env.exists == 'false'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # 根据 Cloudreve 的需求调整

      - name: Set up Android NDK
        if: env.exists == 'false'
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b # 一个较新的稳定版本

      - name: Set up Node.js and Yarn for Frontend Build
        if: env.exists == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm install -g yarn
        if: env.exists == 'false'

      - name: Build Cloudreve Frontend
        if: env.exists == 'false'
        working-directory: ./cloudreve-source
        run: |
          chmod +x ./.build/build-assets.sh
          ./.build/build-assets.sh

      - name: Set up GoReleaser
        if: env.exists == 'false'
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean

      - name: Create .goreleaser.yml for Android Build
        if: env.exists == 'false'
        run: |
          cat <<'EOF' > cloudreve-source/.goreleaser.yml
          project_name: cloudreve
          builds:
            - id: "cloudreve-android"
              main: .
              binary: cloudreve-android-arm64
              env:
                - CGO_ENABLED=1
                - GOOS=android
                - GOARCH=arm64
              goos:
                - android
              goarch:
                - arm64
              ldflags:
                - -s -w -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.BackendVersion=${{ env.latest_tag }}'
          archives:
            - id: "cloudreve-android-archive"
              builds:
                - "cloudreve-android"
              format: zip
              name_template: "cloudreve_${{ env.latest_tag }}_android_arm64"
          release:
            # 你可以留空，goreleaser 会自动从 git tag 中获取
            tag_name: ${{ env.latest_tag }}
            # 从 git log 中自动生成发布说明
            generate_release_notes: true
          EOF

      - name: Build Android Binary with GoReleaser
        if: env.exists == 'false'
        working-directory: ./cloudreve-source
        run: goreleaser build --single-target --clean --snapshot

      - name: Create Release and Upload Binary
        if: env.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.latest_tag }}
          name: "Cloudreve ${{ env.latest_tag }} for Android (arm64)"
          body: |
            Automated build of Cloudreve for Android (arm64).
            Upstream version: ${{ env.latest_tag }}
          files: |
            cloudreve-source/dist/cloudreve_android_arm64.zip
